### ISSUE TITLE
Actor misses phone numbers which contain a slash 

### ISSUE THREAD

**Issue by Sergensen** [vdrmota/Social-Media-and-Contact-Info-Extractor#3]
Hey! 

On pages where the actor could find phone numbers like: 
0175/234234, 0160/345345 and  +49151/456456

It just adds 234234, 345345 and 456456 to the result set "phonesUncertain".

Example: https://sc-eichsfeld.de/vorstand.html

**Comment by jancurn** [comment]
This issue should be reported in https://github.com/apifytech/apify-js instead, since this actor is just using the function `Apify.utils.phonesFromText()` from Apify SDK (see https://sdk.apify.com/docs/api/social#social.phonesFromText). Note that the function says the results might be inaccurate since it only parses the text using regular expressions. To get accurate phone numbers, you'd need to use some AI-based text classifier.
